version: '3.9'

services:
  postgres:
    container_name: backend_db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - backend-network
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


networks:
  backend-network:
    name: backend-network