version: '3.9'

services:
  hvs_pg:
    container_name: hvs_pg
    image: docker.io/postgres:15-alpine
    networks:
      - hvs_backend-network
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - hvs_pg_data:/var/lib/postgresql/data
  hvs_app:
    container_name: hvs_app
    image: gestanestle/server:1.2
    ports:
      - "8080:8080"
    networks:
      - hvs_backend-network
    environment:
      - PG_HOST=hvs_pg
      - PG_PORT=5432

networks:
  hvs_backend-network:
    name: hvs_backend-network

volumes:
  hvs_pg_data:
    name: hvs_pg_data