version: '3.9'

services:
  hvs_pg:
    container_name: hvs_pg
    image: docker.io/postgres:15-alpine
    networks:
      - backend-network
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - hvs_pg_data:/var/lib/postgresql/data
  hvs_app:
    container_name: hvs_app
    image: gestanestle/server:1.0
    ports:
      - "8080:8080"
    networks:
      - backend-network
    environment:
      - PG_HOST=hvs_pg

  pg_local:
    container_name: pg_local
    image: docker.io/postgres:15-alpine
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  backend-network:
    name: backend-network

volumes:
  hvs_pg_data:
    name: hvs_pg_data