version: '3.9'

services:
  hvs_v1_pg:
    container_name: hvs_v1_pg
    image: docker.io/postgres:15-alpine
    networks:
      - hvs_v1_backend-network
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - hvs_v1_pg_data:/var/lib/postgresql/data
  hvs_v1_app:
    container_name: hvs_v1_app
    image: gestanestle/server:1.1
    ports:
      - "8081:8081"
    networks:
      - hvs_v1_backend-network
    environment:
      - PG_HOST=hvs_v1_pg

networks:
  hvs_v1_backend-network:
    name: hvs_v1_backend-network

volumes:
  hvs_v1_pg_data:
    name: hvs_v1_pg_data