version: '3.9'

services:
  daedavote_pg:
    container_name: daedavote_pg
    image: docker.io/postgres:15-alpine
    networks:
      - daedavote_backend-network
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - daedavote_pg_data:/var/lib/postgresql/data
  daedavote_app:
    container_name: daedavote_app
    image: gestanestle/server:latest
    ports:
      - "8081:8080"
    networks:
      - daedavote_backend-network
    environment:
      - PG_HOST=daedavote_pg
      - PG_PORT=5432

networks:
  daedavote_backend-network:
    name: daedavote_backend-network

volumes:
  daedavote_pg_data:
    name: daedavote_pg_data