version: '3.9'

services:
  hvs_pg:
    container_name: hvs_pg
    image: docker.io/postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - backend-network
    environment:
      - POSTGRES_DB=daedalus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  hvs_app:
    container_name: hvs_app
    image: gestanestle/server:1.0
    ports:
      - "8080:8080"
    networks:
      - backend-network
    environment:
      - PG_HOST=hvs_pg

networks:
  backend-network:
    name: backend-network