name: Java CI

on:
  push:
    branches: [ "krimaster" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and Push
        run: mvn clean package jib:build
        env:
          DOCKER_USERNAME: ${{ github.actor }}